package com.sharkjob.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Data
@DynamoDBTable(tableName = "SharkJobInfo")
public class Job {

    @DynamoDBHashKey(attributeName = "jobId")
    @DynamoDBAutoGeneratedKey
    private String jobId;

    @DynamoDBAttribute(attributeName = "jobTittle")
    private String jobTittle;

    @DynamoDBAttribute(attributeName = "jobDescription")
    private String jobDescription;

    @DynamoDBAttribute(attributeName = "company")
    private User company;

    @DynamoDBAttribute(attributeName = "requiredSkills")
    private List<String> requiredSkills;

    @DynamoDBAttribute(attributeName = "startTime")
    private Date startTime;

    @DynamoDBAttribute(attributeName = "expirTime")
    private Date expirTime;

    @DynamoDBAttribute(attributeName = "location")
    private String location;

    @DynamoDBAttribute(attributeName = "categories")
    private String categories;

    @DynamoDBAttribute(attributeName = "comments")
    private ArrayList<Comment> comments;

}
